/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Recipe {
  'id' : bigint,
  'estimatedTimeMinutes' : bigint,
  'difficulty' : string,
  'name' : string,
  'description' : string,
  'steps' : Array<string>,
  'cuisine' : string,
  'isVeg' : boolean,
  'ingredients' : Array<string>,
}
export interface RecipeMatch { 'matchScore' : bigint, 'recipe' : Recipe }
export interface UserProfile {
  'displayName' : string,
  'searchesPerformed' : bigint,
  'favoriteCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'addRecipe' : ActorMethod<[Recipe], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<Recipe>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchRecipes' : ActorMethod<
    [Array<string>, [] | [boolean], [] | [bigint], [] | [string]],
    Array<RecipeMatch>
  >,
  'updateProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];